apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: ashu-app-web
  name: ashu-app-web
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: ashu-app-web
  type: LoadBalancer
status:
  loadBalancer: {}
